### ISSUE TITLE
Setting up 411 on top of an Elastic cluster

### ISSUE THREAD

**Issue by webhead404** [kiwiz/411-docker#7]
Is it possible to install 411 via docker on a host running elasticsearch?

**Comment by kiwiz** [comment]
Yup, you can install it on the host or use the docker image here.

**Comment by webhead404** [comment]
What's the proper command in Docker to do this? We have tried multiple ways but I want to reach 411 over a http proxy and also have 411 reach the ES server on the host.

**Comment by kiwiz** [comment]
The `config.php` file points to `es:9200`. If you update that to `localhost:9200` and do a `docker build`, that should hopefully get you a working image.

**Comment by dataatsky** [comment]
Updating it to localhost:9200 and doing a docker build does not work as it tries to point to the container  instead of the vm where the elastic is. 
I have also tried to set the public_IP:9200 of my elasticsearch but I still got failed state in health section.
I must say that when doing `curl public_IP:9200` inside the container I get:

> {
>   "name" : "d-lXPgA",
>   "cluster_name" : "elasticsearch",
>   "cluster_uuid" : "-il_pkEsTAyTrBoD-_b79w",
>   "version" : {
>     "number" : "6.5.4",
>     "build_flavor" : "default",
>     "build_type" : "deb",
>     "build_hash" : "d2ef93d",
>     "build_date" : "2018-12-17T21:17:40.758843Z",
>     "build_snapshot" : false,
>     "lucene_version" : "7.5.0",
>     "minimum_wire_compatibility_version" : "5.6.0",
>     "minimum_index_compatibility_version" : "5.0.0"
>   },
>   "tagline" : "You Know, for Search"
> }

Which is, the expected behavior and I don't understand why 411 health system still does not get it.

Configuration of config.php as follows:

> # Configuration for the 411 Alerts index.
>     'alerts' => [
>         'hosts' => ['http://public_ip:9200'],
>         'index_hosts' => [],
>         'ssl_cert' => null,
>         'index' => null,
>         'date_based' => false,
>         'date_interval' => null,
>         'date_field' => 'alert_date',
>         'date_type' => null,
>         'src_url' => null,
>     ],
>     # Configuration for the logstash index that 411 queries.
>     'logstash' => [
>         'hosts' => ['http://public_ip:9200'],
>         'index_hosts' => [],
>         'ssl_cert' => null,
>         'index' => '[logstash-]Y.m.d',
>         'date_based' => true,
>         'date_interval' => 'd',
>         'date_field' => '@timestamp',
>         'date_type' => null,
>         'src_url' => null,
>     ],
> ];

When running 411 interface I don't get any errors prompting up.

Could you shed some light on how to resolve this situation?

**Comment by kiwiz** [comment]
Moving all docker config into the main repo (etsy/411). Please reopen an issue there if this is still a problem.
